### ISSUE TITLE
Landing page fails with 503 status

### ISSUE THREAD

**Issue by boredstiff** [adidas/adidas.github.io#23]
Attempting to visit https://adidas.github.io/ results in Nginx responding with a 503 when attempting to hit the following endpoints:

 - https://api.adidas.com/github/repositories
 - https://api.adidas.com/github/content/lang/en
 - https://api.adidas.com/github/content/projects
 - https://api.adidas.com/github/content

**Comment by RecuencoJones** [comment]
Thanks for reporting @boredstiff!
Looks like services were down as docker images were removed from our registry, we are pushing them now.

Will close once they are back up.

**Comment by RecuencoJones** [comment]
Content APIs are back up again, and portal is working as expected.
