### ISSUE TITLE
@adidascareers not owned by Adidas

### ISSUE THREAD

**Issue by mabis** [adidas/adidas.github.io#24]
The Twitter account linked to in the footer (@adidascareers) is not owned/managed by Adidas but someone else

**Comment by moelders** [comment]
Hello @mabis,
I have talked to the team in charge of this and they are already aware of this situation. The account is not used to act against adidas, so, we as a company can not take action.
However, thank you very much for opening the ticket, it is something that could affect and we have to keep an eye on it.
Regards!

**Comment by mabis** [comment]
hey @moelders,

I'd remove the link to it from your footer if I were you but of course up to you.

Cheers

**Comment by moelders** [comment]
Hello @mabis,
We did not realize that the link was still in the portal. Of course, we remove it.
Thank you again.
Regards!

**Comment by moelders** [comment]
We have just updated the link. Thank you very much @mabis.
Regards.
