### ISSUE TITLE
Negative margin on sidebar

### ISSUE THREAD

**Issue by fildon** [adidas/adidas.github.io#30]
![Screenshot 2021-06-16 at 15 46 56](https://user-images.githubusercontent.com/10462288/122231712-eff54680-ceba-11eb-9aa6-b419cde04541.png)

At screen sizes between 110em and 115em wide, the sidebar class gets a negative margin-left value between -5em and -0em.

As shown in the screenshot above this negative margin causes the sidebar to render partially outside the viewport.

Removing the -5em from the highlighted calc correctly repositions the sidebar. However I'm not sure what the original motivation for the -5em was and if removing it can be done safely without impacting some other layout.

**Comment by RecuencoJones** [comment]
Fixed by #31
